#!/usr/bin/env python3
"""Execute or preview an OpenMC experiment matrix.

Matrix execution is intentionally limited to orchestration. Experiment-4 is
responsible for statistical aggregation and figure generation.

For delay campaigns, the matrix expands configurations x delays x replicates.
For the ``rate`` campaign, ``rates_pps`` adds a rate dimension so each rate has
a distinct rate-aware run identifier generated by ``run_experiment.py``.

For rate sweeps, the expected packet count is derived explicitly from the
offered rate and traffic duration:

    expected_packets = rate_pps * duration_s

This value is passed to ``run_experiment.py`` so the functional validation,
destination packet target, expected block count, and manifest all describe the
actual workload generated at each candidate rate.
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import List

ROOT = Path(__file__).resolve().parents[1]


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Run an OpenMC repeated-run matrix."
    )
    parser.add_argument("matrix", help="JSON matrix definition")
    parser.add_argument(
        "--results-root",
        default=str(ROOT / "reproducibility" / "results"),
    )
    parser.add_argument(
        "--deploy-env",
        default=str(ROOT / "config" / "bleo-deployment.env"),
    )
    parser.add_argument(
        "--experiment-env",
        default=str(ROOT / "config" / "bleo-experiment.env"),
    )
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--continue-on-error", action="store_true")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    matrix_path = Path(args.matrix)
    matrix = json.loads(matrix_path.read_text(encoding="utf-8"))

    campaign = matrix["campaign"]
    delays = matrix["delays_ms"]
    rates = matrix.get("rates_pps")
    replicates = int(matrix.get("replicates", 10))
    configurations = matrix["configurations"]
    common = matrix.get("common", {})

    if not isinstance(delays, list) or not delays:
        parser.error("matrix delays_ms must be a non-empty list")

    if replicates < 1:
        parser.error("matrix replicates must be >= 1")

    if not isinstance(configurations, list) or not configurations:
        parser.error("matrix configurations must be a non-empty list")

    if rates is not None:
        if not isinstance(rates, list) or not rates:
            parser.error(
                "matrix rates_pps must be a non-empty list when present"
            )

        rates = [int(rate) for rate in rates]

        if any(rate <= 0 for rate in rates):
            parser.error("matrix rates_pps values must be positive")

        if "rate_pps" in common:
            parser.error(
                "use either rates_pps or common.rate_pps, not both"
            )

        if "expected_packets" in common:
            parser.error(
                "do not set common.expected_packets when using rates_pps; "
                "it is derived from rate_pps * duration_s"
            )

    elif campaign == "rate":
        parser.error(
            "rate campaign requires a non-empty rates_pps list"
        )

    sweep_rates = [None] if rates is None else rates

    commands: List[List[str]] = []

    for configuration in configurations:
        backend = configuration["backend"]
        policy = configuration.get("policy", "default")

        for delay in delays:
            for rate in sweep_rates:
                for replicate in range(1, replicates + 1):

                    command = [
                        sys.executable,
                        str(ROOT / "scripts" / "run_experiment.py"),
                        "--campaign", campaign,
                        "--backend", backend,
                        "--policy", policy,
                        "--delay-b-ms", str(delay),
                        "--replicate", str(replicate),
                        "--results-root", args.results_root,
                        "--deploy-env", args.deploy_env,
                        "--experiment-env", args.experiment_env,
                    ]

                    if rate is not None:
                        command += [
                            "--rate-pps",
                            str(rate),
                        ]

                    option_map = {
                        "delay_a_ms": "--delay-a-ms",
                        "block_size": "--block-size",
                        "repairs": "--repairs",
                        "packet_size": "--packet-size",
                        "rate_pps": "--rate-pps",
                        "duration_s": "--duration-s",
                        "expected_packets": "--expected-packets",
                        "resource_interval_ms":
                            "--resource-interval-ms",
                    }

                    for key, option in option_map.items():
                        if key in common:
                            command += [
                                option,
                                str(common[key]),
                            ]

                    #
                    # Rate-sweep workload derivation.
                    #
                    # run_experiment.py otherwise retains its default
                    # expected_packets=2000.  For a rate sweep that would
                    # make the functional target inconsistent with the
                    # actual traffic workload at rates other than 200 pps.
                    #
                    if rate is not None:
                        duration_s = int(
                            common.get("duration_s", 10)
                        )
                        block_size = int(
                            common.get("block_size", 8)
                        )

                        if duration_s <= 0:
                            parser.error(
                                "common.duration_s must be positive"
                            )

                        if block_size <= 0:
                            parser.error(
                                "common.block_size must be positive"
                            )

                        expected_packets = rate * duration_s

                        if expected_packets % block_size != 0:
                            parser.error(
                                "rate %d pps x duration %d s gives "
                                "%d packets, which is not a multiple "
                                "of block_size=%d"
                                % (
                                    rate,
                                    duration_s,
                                    expected_packets,
                                    block_size,
                                )
                            )

                        command += [
                            "--expected-packets",
                            str(expected_packets),
                        ]

                    if policy == "adaptive":
                        seed_base = int(
                            configuration.get("seed_base", 1000)
                        )
                        command += [
                            "--seed",
                            str(seed_base + replicate),
                        ]

                    if args.dry_run:
                        command.append("--dry-run")

                    if args.force:
                        command.append("--force")

                    commands.append(command)

    rate_text = (
        ""
        if rates is None
        else f", rates={len(rates)}"
    )

    print(
        f"Matrix {matrix_path}: "
        f"campaign={campaign}, "
        f"configurations={len(configurations)}, "
        f"delays={len(delays)}"
        f"{rate_text}, "
        f"replicates={replicates}, "
        f"total_runs={len(commands)}"
    )

    failures = 0

    for index, command in enumerate(commands, 1):
        print(
            f"[{index}/{len(commands)}] "
            f"{' '.join(command)}",
            flush=True,
        )

        result = subprocess.run(command)

        if result.returncode != 0:
            failures += 1

            if not args.continue_on_error:
                return result.returncode

    if failures:
        print(
            f"Matrix completed with "
            f"{failures} failed run(s).",
            file=sys.stderr,
        )
        return 1

    print("Matrix orchestration completed successfully.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
